### ISSUE TITLE
Error with i3wm

### ISSUE THREAD

**Issue by klitztuch** [OkayDave/barr#28]
Getting an Error when trying to click on a workspace.

```
sh: Line 1: barr_i3ipc: Command not found.
```

Tried installing ruby-i3ipc, but no changes

**Comment by OkayDave** [comment]
Thanks for the report. Looks like executable isn't in your `$PATH` for some reason. 

Are you using ruby from a distro repo or is it installed via rvm/rbenv? Is Barr installed via `gem install barr` or another method?

**Comment by klitztuch** [comment]
Hey,
I'm using ruby from my distro repo and barr is installed via gem install barr

**Comment by florianmski** [comment]
Just got the same, `gem install i3ipc` fixed it 👍
