### ISSUE TITLE
won't work [help]

### ISSUE THREAD

**Issue by atayoez** [OkayDave/barr#58]
It looks like lemonbar has some problems executing a non-.sh file or I can't make it work properly

**Comment by OkayDave** [comment]
Lemonbar doesn't execute files directly (it takes the output of another program or script via a pipe) so that bit shouldn't be a problem.

Paste your ruby code and the command you use to launch lemonbar with the script and I'll try and help you out.

**Comment by atayoez** [comment]
./lemonbar.rb | lemonbar -g

**Comment by atayoez** [comment]
ok. It works now
