### ISSUE TITLE
Suggestion: bspwm support

### ISSUE THREAD

**Issue by kdelwat** [OkayDave/barr#7]
I love this project, but I think it would be very helpful to a lot of people if support for BSPWM workspaces was implemented. It shouldn't be too much different from i3, and there's references to the appropriate commands [here](https://github.com/baskerville/bspwm/tree/master/examples). Thanks!

**Comment by OkayDave** [comment]
Yes I'd definitely like to get this done. I don't have `bspwm` set up at the moment so I probably won't be able to get to this until the end of the week at the earliest, but it's definitely going on the todo list.

**Comment by OkayDave** [comment]
I've added a `Bspwm` block in the latest version. I can't be certain that the monitor segregation works properly as I only have a single screen. Otherwise, the desktop display and switching is working nicely.
